### ISSUE TITLE
No CMakeLists.txt in ./modules/external directory

### ISSUE THREAD

**Issue by cyrillsemenov** [landonviator/Viator-Juce-CMake#1]
## Problem:
When we try to configure the project, CMake throws an error:

```
CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /Users/afab/Viator-Juce-CMake/modules/external

  does not contain a CMakeLists.txt file.
``` 

This is expected behaviour because there is a subdirectory added in CMake:

https://github.com/landonviator/Viator-Juce-CMake/blob/a77aa5571395b6167685a6e61ebb15409906c013/CMakeLists.txt#L46

## Solution:

Adding `./modules/external/CMakeLists.txt` with the following content fixes the problem:

```cmake
add_subdirectory(googletest)
```

I found that `./modules` is in the `.gitignore` file, but this is unnecessary because the [contents of this folder are submodules and they are just links to repos, not real files for git](https://www.git-scm.com/docs/gitsubmodules/2.16.6) (well, not exactly but make sense in this context):

https://github.com/landonviator/Viator-Juce-CMake/blob/a77aa5571395b6167685a6e61ebb15409906c013/.gitignore#L5

So I can suggest deleting this line from `.gitignore`

**Comment by landonviator** [comment]
Alright I think I fixed it, thanks for catching that!
